name: 🐛 Bug report
description: Create a bug report
body:
  - type: checkboxes
    attributes:
      label: Are you certain it's a bug?
      description: If you're uncertain, feel free to start a discussion (https://github.com/ivasanpag/react-vnc-playback-viewer/discussions)
      options:
        - label: Yes, it looks like a bug
          required: true
  - type: checkboxes
    attributes:
      label: Are you sure this is not an issue in noVNC?
      description: If this is a Docusaurus issue, report it at https://github.com/novnc/noVNC/issues.
      options:
        - label: It is not a noVNC issue
          required: true
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists
      options:
        - label: I have searched existing issues, it hasn't been reported yet
          required: true
  - type: textarea
    attributes:
      label: Issue description
    validations:
      required: true