blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/ivasanpag/react-vnc-playback-viewer/discussions
    about: Please ask and answer questions on our discussions page.